# Generated by Django 4.1.4 on 2022-12-30 12:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('أراضي زراعية', 'أراضي زراعية'), ('حدائق ريفية', 'حدائق ريفية'), ('قطع زراعية', 'قطع زراعية'), ('مشاركة محاصيل', 'مشاركة محاصيل'), ('الات زراعية', 'الات زراعية'), ('تسويق محاصيل', 'تسويق محاصيل')], max_length=200)),
                ('location', models.CharField(choices=[('Alexandria', 'الإسكندرية'), ('North Sinai', 'شمال سيناء'), ('Aswan', 'أسوان'), ('Asyut', 'أسيوط'), ('Beheira', 'البحيرة'), ('Beni Suef', 'بني سويف'), ('Cairo', 'القاهرة'), ('Dakahlia', 'الدقهلية'), ('Damietta', 'دمياط'), ('Fayyoum', 'الفيوم'), ('Gharbiya', 'الغربية'), ('Giza', 'الجيزة'), ('Helwan', 'حلوان'), ('Ismailia', 'الإسماعيلية'), ('Kafr El Sheikh', 'كفرالشيخ'), ('Luxor', 'الأقصر'), ('Marsa Matrouh', 'مرسى مطروح'), ('Minya', 'المنيا'), ('Monofiya', 'المنوفية'), ('New Valley', 'الوادي الجديد'), ('Port Said', 'بورسعيد'), ('Qalioubiya', 'قليويبة'), ('Qena', 'قنا'), ('Red Sea', 'البحر الأحمر'), ('Sharqiya', 'الشرقية'), ('Sohag', 'سوهاج'), ('South Sinai', 'جنوب سيناء'), ('Suez', 'السويس'), ('Tanta', 'طنطا')], max_length=200)),
                ('description', models.TextField(max_length=600)),
                ('price', models.FloatField(max_length=100)),
                ('expiration_date', models.DateField(default=datetime.date(2023, 1, 2))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/ads')),
                ('advertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertise.advertise')),
            ],
        ),
    ]
