# Generated by Django 4.1.4 on 2022-12-30 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertise', '0005_alter_advertise_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertise', to=settings.AUTH_USER_MODEL),
        ),
    ]
