# Generated by Django 4.1.4 on 2022-12-30 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0006_alter_advertise_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 1, 2), null=True),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
