# Generated by Django 4.1.4 on 2023-01-23 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0007_alter_advertise_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 2, 23), null=True),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='location',
            field=models.CharField(choices=[('الإسكندرية', 'الإسكندرية'), ('شمال سيناء', 'شمال سيناء'), ('أسوان', 'أسوان'), ('أسيوط', 'أسيوط'), ('البحيرة', 'البحيرة'), ('بني سويف', 'بني سويف'), ('القاهرة', 'القاهرة'), ('الدقهلية', 'الدقهلية'), ('دمياط', 'دمياط'), ('الفيوم', 'الفيوم'), ('الغربية', 'الغربية'), ('الجيزة', 'الجيزة'), ('حلوان', 'حلوان'), ('الإسماعيلية', 'الإسماعيلية'), ('كفرالشيخ', 'كفرالشيخ'), ('الأقصر', 'الأقصر'), ('مرسى مطروح', 'مرسى مطروح'), ('المنيا', 'المنيا'), ('المنوفية', 'المنوفية'), ('الوادي الجديد', 'الوادي الجديد'), ('بورسعيد', 'بورسعيد'), ('قليويبة', 'قليويبة'), ('قنا', 'قنا'), ('البحر الأحمر', 'البحر الأحمر'), ('الشرقية', 'الشرقية'), ('سوهاج', 'سوهاج'), ('جنوب سيناء', 'جنوب سيناء'), ('السويس', 'السويس'), ('طنطا', 'طنطا')], max_length=200),
        ),
    ]
