# Generated by Django 4.1.4 on 2023-01-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0008_advertise_is_active_alter_advertise_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertise',
            options={'ordering': ['is_active']},
        ),
    ]
