# Generated by Django 4.1.4 on 2023-01-24 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0009_alter_advertise_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 2, 24), null=True),
        ),
    ]
