# Generated by Django 4.1.4 on 2023-04-08 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0010_alter_advertise_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 9), null=True),
        ),
    ]
