# Generated by Django 4.1.4 on 2023-04-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0011_alter_advertise_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertise',
            name='location',
        ),
    ]
