# Generated by Django 4.1.4 on 2023-04-08 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0012_remove_advertise_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('أراضي زراعية', 'أراضي زراعية'), ('حدائق ريفية', 'حدائق ريفية'), ('قطع زراعية', 'قطع زراعية'), ('مشاركة محاصيل', 'مشاركة محاصيل'), ('الات زراعية', 'الات زراعية'), ('تسويق محاصيل', 'تسويق محاصيل')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='advertise',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertise', to='advertise.category'),
        ),
    ]
