# Generated by Django 4.1.4 on 2023-04-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0014_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
