# Generated by Django 4.1.4 on 2023-04-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0016_advertise_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='advertise.category'),
        ),
    ]
